I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1915, in script
    if pos in ([2,2],[1,3],[3,3],[4,2],[1,5],[3,4],[2,4]):
  File "game/script.rpy", line 1915, in script
    if pos in ([2,2],[1,3],[3,3],[4,2],[1,5],[3,4],[2,4]):
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\Applications\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "E:\Applications\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "E:\Applications\renpy-7.3.5-sdk\renpy\main.py", line 143, in run
    renpy.execution.run_context(True)
  File "E:\Applications\renpy-7.3.5-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "game/script.rpy", line 1915, in script
    if pos in ([2,2],[1,3],[3,3],[4,2],[1,5],[3,4],[2,4]):
  File "game/script.rpy", line 1915, in script
    if pos in ([2,2],[1,3],[3,3],[4,2],[1,5],[3,4],[2,4]):
  File "E:\Applications\renpy-7.3.5-sdk\renpy\execution.py", line 59, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Forgotten One 1.0
Fri Nov 29 01:19:14 2019
